---
display:
  fullscreen: false
  resolution: 720p  # 480p, 720p or 1080p
  pos_x: 1900
  pos_y: 50
  frame_rate: 60
  caption: Partillery
  window_icon: window_icon.png
game:
  named_colours: # define named colours here, then use them in scene -> terrain -> layer
    shiny_snow: 200, 200, 200
    snow: 150, 150, 150
    snow1: 145, 145, 145
    snow2: 140, 140, 140
    snow3: 135, 135, 135
    snow4: 130, 130, 130
    tar: 15, 15, 15
    desert: 198, 154, 107
    mud: 86, 56, 22
  scenes:
    - name: 'calm_night'
      background: 'bg_calm_night.png'
      terrain_layers: # '<named colour>, <layer height in pixels>'. Use '-1' to define single colour throughout or the bottom layer.
        - col: snow
          h: 10
        - col: snow1
          h: 6
        - col: snow2
          h: 6
        - col: snow3
          h: 4
        - col: snow4
          h: 4
        - col: tar
          h: -1

    - name: 'aurora_borealis'
      background: 'bg_aurora_borealis_2.png'
      terrain_layers:
        - col: shiny_snow
          h: -1

    - name: 'desert_night'
      background: 'bg_desert_night.png'
      terrain_layers:
        - col: desert
          h: 20
        - col: mud
          h: -1

  background: 010.png
  height_fraction: 0.8
  tank_width: 32
  tank_height: 16
  move_duration_ms: 3500
game_control_panel:
  img_scale_factor: 3.9
  background_img: control_panel.png
  font_name: expressway.ttf
  font_size_viewer: 16

  # For buttons, windows etc.
  # pos : position variable indicates relative offsets from the top left corner of the control panel
  #       as a percentage of control panel dimensions.
  # The main logo area is given 1/5 of the panel width
  # The rest of the control sets are X_axis centered at 1/5th of the remaining width
  # Placement of flanking inc / dec buttons is fine_tuned by experiment.
  # All values are in percentage of parent surface dimensions
  # Control button groups
  layout:
    weapon_group:
      center_pos: [ 0.3, 0.5 ]
      central:
        name: weapons_list
        clickable: True
        can_lock_mouse: True
        img: weapons_list.png
        img_hover: weapons_list_hover.png
        overlay: viewer
        overlay_w_ratio: 0.94
        overlay_h_ratio: 0.45
        overlay_x_offset: 0.
        overlay_y_offset: 0.38
    move_group:
      center_pos: [ 0.44, 0.65]
      central:
        name: viewer_move
        clickable: False
        can_lock_mouse: False
        img: viewer_move.png
        img_hover: viewer_move.png
        overlay: viewer
        overlay_w_ratio: 1
        overlay_h_ratio: 1
        overlay_x_offset: 0
        overlay_y_offset: 0
      top:
        name: move
        clickable: False
        can_lock_mouse: False
        img: button_move.png
        img_hover: button_move_hover.png
      left:
        name: move_left
        clickable: True
        can_lock_mouse: False
        img: button_dec.png
        img_hover: button_dec_hover.png
      right:
        name: move_right
        clickable: True
        can_lock_mouse: False
        img: button_inc.png
        img_hover: button_inc_hover.png
    angle_group:
      center_pos: [ 0.55, 0.65 ]
      central:
        name: viewer_angle
        clickable: False
        can_lock_mouse: False
        img: viewer_angle.png
        img_hover: viewer_angle.png
        overlay: viewer
        overlay_w_ratio: 1
        overlay_h_ratio: 1
        overlay_x_offset: 0
        overlay_y_offset: 0
      top:
        name: angle
        clickable: True
        can_lock_mouse: True
        img: button_angle.png
        img_hover: button_angle_hover.png
      left:
        name: angle_left
        clickable: True
        can_lock_mouse: False
        img: button_dec.png
        img_hover: button_dec_hover.png
      right:
        name: angle_right
        clickable: True
        can_lock_mouse: False
        img: button_inc.png
        img_hover: button_inc_hover.png
    fire_group:
      center_pos: [ 0.654, 0.5 ]
      central:
        name: fire
        clickable: True
        can_lock_mouse: False
        pos: [ 0.76, 0.5 ]
        img: button_fire.png
        img_hover: button_fire_hover.png
    power_group:
      center_pos: [ 0.77, 0.65 ]
      central:
        name: viewer_power
        clickable: False
        can_lock_mouse: False
        img: viewer_power.png
        img_hover: viewer_power.png
        overlay: viewer
        overlay_w_ratio: 1
        overlay_h_ratio: 1
        overlay_x_offset: 0
        overlay_y_offset: 0
      left:
        name: power_dec
        clickable: True
        can_lock_mouse: False
        img: button_dec.png
        img_hover: button_dec_hover.png
      right:
        name: power_inc
        clickable: True
        can_lock_mouse: False
        img: button_inc.png
        img_hover: button_inc_hover.png
      top:
        name: power_bar
        clickable: True
        can_lock_mouse: True
        img: power_bar.png
        img_hover: power_bar_hover.png
        overlay: value_bar
        overlay_w_ratio: 0.93
        overlay_h_ratio: 0.34
        overlay_x_offset: 0
        overlay_y_offset: 0.5
    scoreboard_group:
      center_pos: [ 0.92, 0.5 ]
      central:
        name: scoreboard
        clickable: False
        can_lock_mouse: False
        img: score_board.png
        img_hover: score_board_hover.png
        overlay: viewer
        overlay_w_ratio: 0.94
        overlay_h_ratio: 0.91
        overlay_x_offset: 0.01
        overlay_y_offset: 0
physics:
  gravity: -500
  base_speed: 1000
tank:
  width: 16
  height: 32
