---
display:
  width: 1280
  height: 720
  pos_x: 100
  pos_y: 40
  frame_rate: 60
  caption: 'Partillery'
  window_icon: 'window_icon.png'
game_area:
  height_fraction: 0.8
game_control_panel:
  img_scale_factor: 15
  background_img: 'control_panel.png'
  font: 'expressway.ttf'
  font_size_window: 13
  font_size_heading: 15
physics:
  gravity: 500
  base_speed: 10
tank:
  width: 16
  height: 32
player:
  default_power: 50
  default_turret_angle_player1: 60
  default_turret_angle_player2: 120
